ISO_TO_NAME = {
    "arg": "Argentina",
    "atl": "Austria",         
    "aus": "Australia",
    "bah": "Bahrain",
    "ban": "Bangladesh",
    "bel": "Belgium",
    "bra": "Brazil",
    "bul": "Bulgaria",
    "can": "Canada",
    "chi": "Chile",
    "chn": "China",
    "col": "Colombia",
    "cro": "Croatia",
    "cze": "Czechia",
    "den": "Denmark",
    "egy": "Egypt",
    "est": "Estonia",
    "fin": "Finland",
    "fra": "France",
    "ger": "Germany",
    "gre": "Greece",
    "hkg": "Hong Kong",
    "hun": "Hungary",
    "ido": "Indonesia",
    "ind": "India",
    "ire": "Ireland",
    "ita": "Italy",
    "jap": "Japan",
    "jor": "Jordan",
    "kaz": "Kazakhstan",
    "ken": "Kenya",
    "kuw": "Kuwait",
    "leb": "Lebanon",
    "lit": "Lithuania",
    "mal": "Malaysia",
    "mau": "Mauritius",
    "mex": "Mexico",
    "mor": "Morocco",
    "net": "Netherlands",
    "nig": "Nigeria",
    "nor": "Norway",
    "nzl": "New Zealand",
    "oma": "Oman",
    "pak": "Pakistan",
    "per": "Peru",
    "phi": "Philippines",
    "pol": "Poland",
    "por": "Portugal",
    "qat": "Qatar",
    "rom": "Romania",
    "rus": "Russia",
    "ser": "Serbia",
    "sin": "Singapore",
    "slo": "Slovenia",
    "soa": "South Africa",
    "sok": "South Korea",
    "spa": "Spain",
    "sri": "Sri Lanka",
    "swe": "Sweden",
    "swi": "Switzerland",
    "tai": "Taiwan",
    "tha": "Thailand",
    "tun": "Tunisia",
    "tur": "Turkey",
    "ukr": "Ukraine",
    "uni": "United Kingdom",
    "usa": "United States",
    "vie": "Vietnam",
}

FF12_LABELS = {
    1: "Consumer Nondurables",
    2: "Consumer Durables",
    3: "Manufacturing",
    4: "Energy",
    5: "Chemicals",
    6: "Business Equipment",
    7: "Telecommunication",
    8: "Utilities",
    9: "Wholesale / Retail",
    10: "Healthcare",
    11: "Finance",
    12: "Other",
}
